title: PHANTASM
baseurl: ""
email: afshinpaydar@gmail.com
description: >-
 Afshin Paydar
url: "https://www.afshinpaydar.com"
twitter_username: paydar_afshin
github_username:  afshinpaydar


author: Afshin

copyright: "Afshin Paydar"
linkedin_username: afshinpaydar
youtube_username: channel/UCNCqCYfnbG_ntWaniX1Gm9A

plugins:
  - jekyll-feed
