title: Afshin's blog
baseurl: ""
email: afshinpaydar@gmail.com
description: >-
 Afshin Paydar
url: "https://afshinpaydar-binary.github.io"
twitter_username: paydar_afshin
github_username:  afshinpaydar


author: Afshin

copyright: "Afshin Paydar"
linkedin_username: afshinpaydar
youtube_username: channel%2FUCNCqCYfnbG_ntWaniX1Gm9A

plugins:
  - jekyll-feed
