title: PHANTASM
baseurl: ""
#repository: afshinpaydar-binary
email: afshinpaydar@gmail.com
description: >-
 G33k personal blog
url: "https://afshinpaydar.com"
twitter_username: paydar_afshin
github_username:  afshinpaydar


author: Afshin

copyright: "Phantasm"
linkedin_username: afshinpaydar
youtube_username: Afshin Paydar

plugins:
  - jekyll-feed
