title: PHANTASM
email: afshinpaydar@gmail.com
description: >-
 G33k personal blog
baseurl: "/"
url: "https://afshinpaydar.com"
twitter_username: tayebeKavousi
github_username:  tayebe-kavousi


author: Afshin

copyright: "Phantasm"
linkedin_username: afshinpaydar
youtube_username: myYouTube

plugins:
  - jekyll-feed
